//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace READOO.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Keywords.log")]
        public string KeywordsLog {
            get {
                return ((string)(this["KeywordsLog"]));
            }
            set {
                this["KeywordsLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Keywords_ForHumans.txt")]
        public string KeywordsLogForHumans {
            get {
                return ((string)(this["KeywordsLogForHumans"]));
            }
            set {
                this["KeywordsLogForHumans"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("LOGS")]
        public string LogsDirectory {
            get {
                return ((string)(this["LogsDirectory"]));
            }
            set {
                this["LogsDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xml/pagetitles.xml")]
        public string PageTitleXML {
            get {
                return ((string)(this["PageTitleXML"]));
            }
            set {
                this["PageTitleXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("xml/hotsearches.xml")]
        public string HotSearchesXML {
            get {
                return ((string)(this["HotSearchesXML"]));
            }
            set {
                this["HotSearchesXML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IllNeverBeCaught|MeNeither")]
        public string UnwantedKeywords {
            get {
                return ((string)(this["UnwantedKeywords"]));
            }
            set {
                this["UnwantedKeywords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int RunsBeforeCleaning {
            get {
                return ((int)(this["RunsBeforeCleaning"]));
            }
            set {
                this["RunsBeforeCleaning"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MinimumOccurrencesToKeep {
            get {
                return ((int)(this["MinimumOccurrencesToKeep"]));
            }
            set {
                this["MinimumOccurrencesToKeep"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ex*.log")]
        public string SystemLogFormat {
            get {
                return ((string)(this["SystemLogFormat"]));
            }
            set {
                this["SystemLogFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("People searched these terms to get here: ")]
        public string HTMLText {
            get {
                return ((string)(this["HTMLText"]));
            }
            set {
                this["HTMLText"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Keywords.log")]
        public string default_KeywordsLog {
            get {
                return ((string)(this["default_KeywordsLog"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Keywords_ForHumans.txt")]
        public string default_KeywordsLogForHumans {
            get {
                return ((string)(this["default_KeywordsLogForHumans"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\WINDOWS\\system32\\LogFiles\\W3SVC1")]
        public string default_LogsDirectory {
            get {
                return ((string)(this["default_LogsDirectory"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../xml/pagetitles.xml")]
        public string default_PageTitlesXML {
            get {
                return ((string)(this["default_PageTitlesXML"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("../xml/hotsearches.xml")]
        public string default_HotSearchesXML {
            get {
                return ((string)(this["default_HotSearchesXML"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("IllNeverBeCaught|MeNeither")]
        public string default_UnwantedKeywords {
            get {
                return ((string)(this["default_UnwantedKeywords"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int default_RunsBeforeCleaning {
            get {
                return ((int)(this["default_RunsBeforeCleaning"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int default_MinimumOccurrencesToKeep {
            get {
                return ((int)(this["default_MinimumOccurrencesToKeep"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ex*.log")]
        public string default_SystemLogFormat {
            get {
                return ((string)(this["default_SystemLogFormat"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("People searched these terms to get here: ")]
        public string default_HTMLText {
            get {
                return ((string)(this["default_HTMLText"]));
            }
            set {
                this["default_HTMLText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool defaultServerSettings {
            get {
                return ((bool)(this["defaultServerSettings"]));
            }
            set {
                this["defaultServerSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("windows")]
        public string chosenOS {
            get {
                return ((string)(this["chosenOS"]));
            }
            set {
                this["chosenOS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PlainText {
            get {
                return ((bool)(this["PlainText"]));
            }
            set {
                this["PlainText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool XML {
            get {
                return ((bool)(this["XML"]));
            }
            set {
                this["XML"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool deliminatedFlatFile {
            get {
                return ((bool)(this["deliminatedFlatFile"]));
            }
            set {
                this["deliminatedFlatFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("html|asp|aspx|net|php|xhtml")]
        public string extensions {
            get {
                return ((string)(this["extensions"]));
            }
            set {
                this["extensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("html|asp|aspx|net|php|xhtml")]
        public string default_extensions {
            get {
                return ((string)(this["default_extensions"]));
            }
            set {
                this["default_extensions"] = value;
            }
        }
    }
}
