namespace READOO
{
    partial class WelcomeWindow
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.WelcomePanel = new System.Windows.Forms.Panel();
            this.label5 = new System.Windows.Forms.Label();
            this.creditsAndLicense = new System.Windows.Forms.Label();
            this.pictureBox1 = new System.Windows.Forms.PictureBox();
            this.RunReadooNow = new System.Windows.Forms.Button();
            this.Settings = new System.Windows.Forms.Button();
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.label1 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label8 = new System.Windows.Forms.Label();
            this.WelcomePanel.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).BeginInit();
            this.groupBox1.SuspendLayout();
            this.SuspendLayout();
            // 
            // label2
            // 
            this.label2.BackColor = System.Drawing.Color.Transparent;
            this.label2.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label2.Location = new System.Drawing.Point(6, 16);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(527, 70);
            this.label2.TabIndex = 7;
            this.label2.Text = "READOO reads the logs generated by your server. Looking at what people searched i" +
                "n Google and top search engines, it finds exactly what people are looking for wh" +
                "en they come to you.";
            // 
            // label3
            // 
            this.label3.BackColor = System.Drawing.Color.Transparent;
            this.label3.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label3.Location = new System.Drawing.Point(6, 135);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(527, 50);
            this.label3.TabIndex = 8;
            this.label3.Text = "Then you\'re left with pages of weighted, tasty, targeted keywords.";
            // 
            // label4
            // 
            this.label4.BackColor = System.Drawing.Color.Transparent;
            this.label4.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label4.Location = new System.Drawing.Point(6, 196);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(339, 27);
            this.label4.TabIndex = 9;
            this.label4.Text = "Readable, printable, and XML ready includes. ";
            // 
            // WelcomePanel
            // 
            this.WelcomePanel.Controls.Add(this.label8);
            this.WelcomePanel.Controls.Add(this.label7);
            this.WelcomePanel.Controls.Add(this.label6);
            this.WelcomePanel.Controls.Add(this.label5);
            this.WelcomePanel.Controls.Add(this.creditsAndLicense);
            this.WelcomePanel.Controls.Add(this.pictureBox1);
            this.WelcomePanel.Controls.Add(this.RunReadooNow);
            this.WelcomePanel.Controls.Add(this.Settings);
            this.WelcomePanel.Controls.Add(this.groupBox1);
            this.WelcomePanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.WelcomePanel.Location = new System.Drawing.Point(0, 0);
            this.WelcomePanel.MaximumSize = new System.Drawing.Size(577, 412);
            this.WelcomePanel.MinimumSize = new System.Drawing.Size(577, 412);
            this.WelcomePanel.Name = "WelcomePanel";
            this.WelcomePanel.Size = new System.Drawing.Size(577, 412);
            this.WelcomePanel.TabIndex = 10;
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(222, 46);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(340, 13);
            this.label5.TabIndex = 33;
            this.label5.Text = "NOT READY. EDIT HARVESTKEYWORDS TO USE TODAYS DATE";
            // 
            // creditsAndLicense
            // 
            this.creditsAndLicense.AutoSize = true;
            this.creditsAndLicense.Font = new System.Drawing.Font("Microsoft Sans Serif", 9F, System.Drawing.FontStyle.Underline, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.creditsAndLicense.Location = new System.Drawing.Point(19, 373);
            this.creditsAndLicense.Name = "creditsAndLicense";
            this.creditsAndLicense.Size = new System.Drawing.Size(132, 15);
            this.creditsAndLicense.TabIndex = 32;
            this.creditsAndLicense.Text = "CREDITS &&&& LICENSE";
            this.creditsAndLicense.MouseLeave += new System.EventHandler(this.creditsAndLicense_MouseLeave);
            this.creditsAndLicense.Click += new System.EventHandler(this.creditsAndLicense_Click);
            this.creditsAndLicense.MouseEnter += new System.EventHandler(this.creditsAndLicense_MouseEnter);
            // 
            // pictureBox1
            // 
            this.pictureBox1.Image = global::READOO.Properties.Resources.BANNER;
            this.pictureBox1.Location = new System.Drawing.Point(12, 12);
            this.pictureBox1.Name = "pictureBox1";
            this.pictureBox1.Size = new System.Drawing.Size(550, 90);
            this.pictureBox1.SizeMode = System.Windows.Forms.PictureBoxSizeMode.AutoSize;
            this.pictureBox1.TabIndex = 15;
            this.pictureBox1.TabStop = false;
            // 
            // RunReadooNow
            // 
            this.RunReadooNow.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.RunReadooNow.BackColor = System.Drawing.SystemColors.Control;
            this.RunReadooNow.Image = global::READOO.Properties.Resources.run_Readoo;
            this.RunReadooNow.Location = new System.Drawing.Point(406, 362);
            this.RunReadooNow.Name = "RunReadooNow";
            this.RunReadooNow.Size = new System.Drawing.Size(159, 38);
            this.RunReadooNow.TabIndex = 0;
            this.RunReadooNow.UseVisualStyleBackColor = true;
            this.RunReadooNow.Click += new System.EventHandler(this.RunReadooNow_Click);
            // 
            // Settings
            // 
            this.Settings.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.Settings.Image = global::READOO.Properties.Resources.settings;
            this.Settings.Location = new System.Drawing.Point(291, 362);
            this.Settings.Name = "Settings";
            this.Settings.Size = new System.Drawing.Size(109, 38);
            this.Settings.TabIndex = 10;
            this.Settings.UseVisualStyleBackColor = true;
            this.Settings.Click += new System.EventHandler(this.Settings_Click);
            // 
            // groupBox1
            // 
            this.groupBox1.Controls.Add(this.label4);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.label3);
            this.groupBox1.Location = new System.Drawing.Point(12, 108);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.Size = new System.Drawing.Size(550, 234);
            this.groupBox1.TabIndex = 14;
            this.groupBox1.TabStop = false;
            // 
            // label1
            // 
            this.label1.BackColor = System.Drawing.Color.Transparent;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 12F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(6, 86);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(527, 49);
            this.label1.TabIndex = 13;
            this.label1.Text = "If you want, it picks the very best long-tailed keywords for every page.";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(213, 65);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(351, 13);
            this.label6.TabIndex = 34;
            this.label6.Text = "MUST WORK REGARDLESS OF WHICH LOG FIELDS ARE ENABLED";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(222, 83);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(184, 13);
            this.label7.TabIndex = 35;
            this.label7.Text = "MUST PROMPT FOR C-REFERRER";
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Location = new System.Drawing.Point(410, 84);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(129, 13);
            this.label8.TabIndex = 36;
            this.label8.Text = "X/LAMPP DEFAULT DIR";
            // 
            // WelcomeWindow
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(577, 412);
            this.Controls.Add(this.WelcomePanel);
            this.MaximumSize = new System.Drawing.Size(593, 448);
            this.MinimumSize = new System.Drawing.Size(593, 448);
            this.Name = "WelcomeWindow";
            this.Text = "READOO";
            this.WelcomePanel.ResumeLayout(false);
            this.WelcomePanel.PerformLayout();
            ((System.ComponentModel.ISupportInitialize)(this.pictureBox1)).EndInit();
            this.groupBox1.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Button RunReadooNow;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Panel WelcomePanel;
        public System.Windows.Forms.Button Settings;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.PictureBox pictureBox1;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label creditsAndLicense;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label8;
    }
}

